/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://6te2sxo3hjfbjktu4orha3kawu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zsp3we7zxbf5jnbc447rhhqkoa",
    "aws_cognito_identity_pool_id": "eu-west-2:4e6e5977-6ae7-49df-8ffd-ee8cfc9eec0c",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_UmlZt9YcU",
    "aws_user_pools_web_client_id": "5o2672f67f8t8vcbpphlfank9r",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
